FROM fedora:28

RUN dnf install -y \
	bison \
	cmake \
	make \
	flex \
	git \
	elfutils-devel \
	elfutils-libelf-devel \
	llvm-devel \
	clang \
	clang-devel \
	zlib-devel \
	ncurses-devel \
	elfutils-libelf-devel-static

COPY build.sh /build.sh
ENTRYPOINT ["/bin/sh", "/build.sh"]
