FROM ubuntu:bionic
RUN apt-get update && apt-get install -y \
    bison \
    cmake \
    flex \
    g++ \
    git \
    clang-5.0 \
    libclang-5.0-dev \
    libelf-dev \
    llvm-5.0-dev \
    zlib1g-dev

ENV LLVM_DIR /usr/lib/llvm-5.0

COPY build.sh /build.sh
ENTRYPOINT ["bash", "/build.sh"]
