FROM fedora:29

RUN dnf install -y \
	bison \
	cmake \
	flex \
	git \
	elfutils-devel \
	elfutils-libelf-devel \
	elfutils-libelf-devel-static \
	llvm \
	llvm-devel \
	clang \
	clang-devel \
	zlib-devel \
	ncurses-devel \
	ncurses-static \
	libstdc++-static

ENV LLVM_DIR /usr/lib64/llvm

COPY build.sh /build.sh
ENTRYPOINT ["/bin/sh", "/build.sh"]
